// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearCompleted': string;
  'count': string;
  'filters': string;
  'normal': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
